base_url = "https://seadve.github.io"
title = "SeaDve"
description = "Application developer based in the Philippines"
author = "seadve"

generate_feeds = true
compile_sass = true
minify_html = true
build_search_index = true

theme = "tabi"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
external_links_target_blank = true
highlight_code = true
highlight_theme = "css"
default_language = "en"

[extra]
remote_repository_url = "https://github.com/SeaDve/seadve.github.io"

favicon = "/img/logo-circle.png"
favicon_emoji = ""

social_media_card = "/img/logo.png"

custom_subset = false
theme_switcher = false

menu = [
    { name = "Posts", url = "blog", trailing_slash = true },
    { name = "Projects", url = "projects", trailing_slash = true },
    { name = "Designs", url = "designs", trailing_slash = true },
    { name = "Photographs", url = "photographs", trailing_slash = true },
    { name = "About", url = "about", trailing_slash = true },
]

quick_navigation_buttons = true
show_previous_next_article_links = true

feed_icon = true
full_content_in_feed = true
enable_cards_tag_filtering = true

email = "ZGF2ZWNydXo0OEBnbWFpbC5jb20="
socials = [
    { name = "github", url = "https://github.com/SeaDve/", icon = "github" },
    { name = "gitlab", url = "https://gitlab.gnome.org/SeaDve", icon = "gitlab" },
    { name = "linkedin", url = "https://www.linkedin.com/in/dave-patrick-caberto", icon = "linkedin" },
    { name = "strava", url = "https://www.strava.com/athletes/seadve", icon = "strava" },
    { name = "hevy", url = "https://hevy.com/user/seadve", icon = "hevy" },
]
footer_menu = [
    { name = "Donate", url = "donate", trailing_slash = true },
    { name = "Archive", url = "archive", trailing_slash = true },
    { name = "Tags", url = "tags", trailing_slash = true },
    { name = "Site Statistics", url = "https://seadve.goatcounter.com/", trailing_slash = true },
]
copyright = "Copyright © $CURRENT_YEAR Dave Patrick Caberto. All rights reserved."

allowed_domains = [
    { directive = "font-src", domains = ["'self'", "data:"] },
    { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
    { directive = "media-src", domains = ["'self'", "https://cdn.jsdelivr.net/"] },
    { directive = "script-src", domains = ["'self'"] },
    { directive = "style-src", domains = ["'self'", "'unsafe-inline'"] },
    { directive = "frame-src", domains = ["player.vimeo.com", "https://www.youtube-nocookie.com", "https://www.google.com", "googleads.g.doubleclick.net", "tpc.googlesyndication.com", "ep2.adtrafficquality.google"] },
    { directive = "connect-src", domains = ["'self'", "ep1.adtrafficquality.google", "fundingchoicesmessages.google.com"] },
]

[extra.analytics]
service = "goatcounter"
id = "seadve"
self_hosted_url = ""

[extra.giscus]
enabled_for_all_posts = true
automatic_loading = true
repo = "SeaDve/seadve.github.io"
repo_id = "MDEwOlJlcG9zaXRvcnkzNDAyMTk0NzU"
category = "Announcements"
category_id = "DIC_kwDOFEdWU84CmO-D"
mapping = "slug"
strict_title_matching = 1
enable_reactions = 1
comment_box_above_comments = true
light_theme = "noborder_light"
dark_theme = "noborder_dark"
lang = ""
lazy_loading = true
