base_url = "https://seadve.github.io"
title = "SeaDve"
description = "Application developer based in the Philippines"
author = "seadve"

generate_feed = true
compile_sass = true
minify_html = true
build_search_index = true

theme = "tabi"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
external_links_target_blank = true
highlight_code = true
highlight_theme = "css"
default_language = "en"

[extra]
favicon = "/img/logo.png"
favicon_emoji = ""

headerImage = "/img/banner.png"

menu = [
    { name = "Blog", url = "blog/" },
    { name = "Tags", url = "tags/" },
    { name = "Portfolio", url = "portfolio/" },
    { name = "About", url = "about/" },
]

feed_icon = true
socials = [
    { name = "GitHub", url = "https://github.com/SeaDve/", icon = "github" },
    { name = "GitLab", url = "https://gitlab.gnome.org/SeaDve", icon = "gitlab" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/dave-patrick-caberto", icon = "linkedin" },
    { name = "Mastodon", url = "https://mastodon.social/@seadve", icon = "mastodon" },
]
