base_url = "https://seadve.github.io"
title = "SeaDve"
description = "Application developer based in the Philippines"
author = "seadve"

generate_feeds = true
compile_sass = true
minify_html = true
build_search_index = true

theme = "tabi"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
external_links_target_blank = true
highlight_code = true
highlight_theme = "css"
default_language = "en"

[extra]
remote_repository_url = "https://github.com/SeaDve/seadve.github.io"

favicon = "/img/logo-circle.png"
favicon_emoji = ""

social_media_card = "/img/logo.png"

custom_subset = false
theme_switcher = false

menu = [
    { name = "Blog", url = "blog", trailing_slash = true },
    { name = "Designs", url = "designs", trailing_slash = true },
    { name = "Photographs", url = "photographs", trailing_slash = true },
    { name = "Projects", url = "projects", trailing_slash = true },
    { name = "About", url = "about", trailing_slash = true },
]

quick_navigation_buttons = true

feed_icon = true
full_content_in_feed = true

email = ""
socials = [
    { name = "github", url = "https://github.com/SeaDve/", icon = "github" },
    { name = "gitlab", url = "https://gitlab.gnome.org/SeaDve", icon = "gitlab" },
    { name = "linkedin", url = "https://www.linkedin.com/in/dave-patrick-caberto", icon = "linkedin" },
    { name = "mastodon", url = "https://mastodon.social/@seadve", icon = "mastodon" },
]
footer_menu = [
    { name = "Archive", url = "archive", trailing_slash = true },
    { name = "Tags", url = "tags", trailing_slash = true },
    { name = "Donate", url = "donate", trailing_slash = true },
]
copyright = "Copyright © 2025 Dave Patrick Caberto. All rights reserved."

[extra.giscus]
enabled_for_all_posts = true
automatic_loading = true
repo = "SeaDve/seadve.github.io"
repo_id = "MDEwOlJlcG9zaXRvcnkzNDAyMTk0NzU"
category = "Announcements"
category_id = "DIC_kwDOFEdWU84CmO-D"
mapping = "slug"
strict_title_matching = 1
enable_reactions = 1
comment_box_above_comments = true
light_theme = "noborder_light"
dark_theme = "noborder_dark"
lang = ""
lazy_loading = true
