on:
  push:
    branches: [main]
  pull_request:

name: CI

jobs:
  btypos:
    name: Typos
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check for typos
        uses: crate-ci/typos@master
